export const en = {
  halo: 'Hello',
  selamatDatang: 'Welcome to Use it',
  pointPengguna: 'User Point',
  cari: 'Search',
  daftarAtauLoginUntukLanjut: 'Please Sign Up or Log In to continue',
  daftarMenggunakan: 'Sign Up with',
  loginKeAkunSaya: 'Log in to my account',
  daftar: 'Sign Up',
  masukkanDataDiri: 'Enter your credentials',
  alamatEmail: 'Email Address',
  namaLengkap: 'Full Name',
  nomorHP: 'Phone Number',
  contoh: 'Example',
  kataSandi: 'Password',
  konfirmasiKataSandi: 'Confirm Password',
  sudahMemilikiAkun: 'Already have an account',
  loginDisini: 'Log In instead',
  selamatDatangKembali: 'Welcome Back',
  loginUntukLanjut: 'Please Log In to continue',
  lupaPassword: 'Forgot Password',
  login: 'Log In',
  atauLoginMenggunakan: 'or Log In with',
  silahkanMasukkanEmail: 'Please enter your email address',
  submit: 'Submit',
  profilAkun: 'Account Profile',
  hariSaja: 'Days',
  mingguSaja: 'Weeks',
  bulanSaja: 'Months',
  tahunSaja: 'Years',
  hari: {
    minggu: 'Sunday',
    senin: 'Monday',
    selasa: 'Tuesday',
    rabu: 'Wednesday',
    kamis: 'Thursday',
    jumat: 'Friday',
    sabtu: 'Saturday',
  },
  bulan: {
    jan: 'January',
    feb: 'February',
    mar: 'March',
    apr: 'April',
    mei: 'May',
    jun: 'June',
    jul: 'July',
    agu: 'August',
    sep: 'September',
    okt: 'October',
    nov: 'November',
    des: 'December',
  },
  keLogin: 'To Log In',
  intro1: `Use it can help you\nin managing waste`,
  intro2: `You can do waste related\n transactions, recycling, and consulting`,
  intro3: `Use it is easy to access\nsecure, and reliable`,
  intro4: `Use it motto is\n"From waste to Profit"`,
  rekomendasi: `Recommendation`,
  lihatSemuaProduk: `See All Products`,
  jualLimbah: `Sell Wastes`,
  transfer: `Withdraw`,
  isiSaldo: `Top Up`,
  lokasiSaatIni: `Current Location`,
  tentukanLokasi: `Adjust Location`,
  pengolahanLimbah: `Waste Recycle`,
  kategori: `Categories`,
  beritaDanInformasi: `News & Information`,
  diverifikasi: `Verified`,
  beli: `Buy`,
  jual: `Sell`,
  selesai: `Done`,
  pesananSelesai: `Order Finished`,
  home: `Home`,
  transaksi: `Transaction`,
  penjualan: `Sales`,
  pesan: `Messages`,
  profil: `Profile`,
  jenisLimbah: `Waste Category`,
  stokAwal: `Stock`,
  harga: `Price`,
  kurir: `Courier`,
  deskripsi: `Description`,
  fotoProduk: `Photos of Products`,
  keranjang: `Cart`,
  totalHarga: `Total Price`,
  saring: `Filter`,
  urutkan: `Sort`,
  terjual: `Sold`,
  pembelianMinimum: `Minimum Purchase`,
  stok: `Stocks`,
  biayaMulaiDari: `Cost Starting From`,
  produkTerkait: `Related Products`,
  pesanan: `Orders`,
  siapKirim: `Ready to Send`,
  aktif: `Active`,
  tidakAktif: `Inactive`,
  akun: `Account`,
  riwayatSaldo: `Balance History`,
  pengaturanAkun: `Account Settings`,
  aplikasi: `Application`,
  pengaturanAplikasi: `Application Settings`,
  kebijakanPrivasi: `Privacy Policy`,
  syaratDanKetentuan: `Terms and Conditions`,
  tentangKami: `About Us`,
  logout: `Log Out`,
  selesai: `Done`,
  dikonfirmasi: `Confirmed`,
  dibatalkan: 'Cancelled',
  daftarPenjualan: `Listed Items`,
  judulAlertGagal: `Oops`,
  errorEmailKosong: `Email can't be empty`,
  errorPasswordKosong: `Password can't be empty`,
  errorNamaLengkapKosong: `Full Name can't be empty`,
  errorNomorHPKosong: `Phone Number can't be empty`,
  errorKonfirmasiPasswordKosong: `Confirm Password can't be empty`,
  errorFormatEmail: `Email format must be valid`,
  errorDigitNomorHP: `Nomor HP minimal 7 digit`,
  errorKonfirmasiPasswordTidakCocok: `Password doesn't match`,
  masukkanPin: `Insert PIN`,
  masukkanUlangPin: `Re-Insert PIN`,
  pinTidakSama: `Pin doesn't match`,
  errorPasswordKurangDigit: `Password can't be less than 4 digit`,
  judulAlertBerhasil: `Success`,
  signUpBerhasil: `Sign Up success, please log in to continue`,
  notifikasi: `Notification`,
  terakhirDikunjungi: `Last Visited`,
  loginMenggunakanAkunLain: `Log In With Another Account`,
  signUpLagi: `Sign Up Again Here`,
  cekEmailOtpResetPassword: `Please check your email and insert OTP to reset your password`,
  resetPasswordBerhasil: `Reset Password success, please log in using your new password to continue`,
  resetPassword: `Reset Password`,
  silahkanBuatPasswordBaru: `Please make a new password`,
  apakahAndaYakin: `Are you sure?`,
  apakahAndaYakinSignUp: `Are you sure you want to cancel user verification? You can verify again by logging in into your account`,
  apakahAndaYakinResetPassword: `Are you sure you want to cancel Reset Password verification?`,
  apakahAndaYakinLogin: `Are you sure you want to cancel user verification? OTP verification is needed for application usage`,
  silahkanKetikProdukYangDicari: `Please type the product you are looking for`,
  produkTidakDitemukan: `Product not found`,
  namaProduk: `Product Name`,
  kirimUlangOtp: `Resend OTP`,
  cekEmailUntukOtp: `Check your email for OTP code`,
  sebelumMelanjutkanBuatPin: `Before continuing, you have to create PIN for transaction safety`,
  lanjut: `Continue`,
  selamatDatangdiUseIt: `Welcome to Use it, you can do any transaction related to waste here`,
  apakahAndaYakinKeluar: `Are you sure you want to close Use it?`,
  namaPenjual: 'Seller Name',
  namaTokoAtauLembaga: 'Merchant / Market Name',
  alamat: `Address`,
  satuan: `Unit Type`,
  ya: 'Yes',
  tidak: 'No',
  apakahAndaYakinHapusGambar: 'Are you sure you want to delete photo',
  produk: `Products`,
  cartKosong: `Cart is Empty`,
  apakahandaYakinHapusProduk: `Are you sure you want to delete product`,
  apakahAndaYakinHapusCart: `Are you sure you want to reset cart`,
  andaHarusLogin: 'You have to Log In or Sign Up to use this feature',
  tidakSekarang: 'Not now',
  kategoriTidakDitemukan: 'Category not found',
  dataBelumTersedia: 'Data is empty',
  tambahProduk: 'Add Product',
  kuantitas: 'Quantity',
  perkiraanKuantitas: 'Estimated Quantity',
};
