export const id = {
  halo: 'Halo',
  selamatDatang: 'Selamat Datang di Use it',
  pointPengguna: 'Point Pengguna',
  cari: 'Cari',
  daftarAtauLoginUntukLanjut:
    'Silahkan Mendaftar atau Log In untuk melanjutkan',
  daftarMenggunakan: 'Daftar menggunakan',
  loginKeAkunSaya: 'Log In ke akun saya',
  daftar: 'Daftar',
  masukkanDataDiri: 'Masukkan data diri anda',
  alamatEmail: 'Alamat Email',
  namaLengkap: 'Nama Lengkap',
  nomorHP: 'Nomor HP',
  contoh: 'Contoh',
  kataSandi: 'Password',
  konfirmasiKataSandi: 'Konfirmasi Password',
  sudahMemilikiAkun: 'Sudah Memiliki Akun',
  loginDisini: 'Log In disini',
  selamatDatangKembali: 'Selamat Datang Kembali',
  loginUntukLanjut: 'Silahkan Log In untuk melanjutkan',
  lupaPassword: 'Lupa Password',
  login: 'Log In',
  atauLoginMenggunakan: 'atau Log In menggunakan',
  silahkanMasukkanEmail: 'Silahkan memasukkan alamat email anda',
  submit: 'Submit',
  profilAkun: 'Profil Akun',
  hariSaja: 'Hari',
  mingguSaja: 'Mingu',
  bulanSaja: 'Bulan',
  tahunSaja: 'Tahun',
  hari: {
    minggu: 'Minggu',
    senin: 'Senin',
    selasa: 'Selasa',
    rabu: 'Rabu',
    kamis: 'Kamis',
    jumat: 'Jumat',
    sabtu: 'Sabtu',
  },
  bulan: {
    jan: 'Januari',
    feb: 'Februari',
    mar: 'Maret',
    apr: 'April',
    mei: 'Mei',
    jun: 'Juni',
    jul: 'Juli',
    agu: 'Agustus',
    sep: 'September',
    okt: 'Oktober',
    nov: 'November',
    des: 'Desember',
  },
  keLogin: 'Ke Log In',
  intro1: `Use it dapat membantu anda\ndalam mengelola limbah`,
  intro2: `Anda dapat melakukan\njual beli, pengolahan, dan konsultasi`,
  intro3: `Use it merupakan platform yang\nmudah di akses, aman, dan terpercaya`,
  intro4: `Semangat Use it adalah\n"From waste to Profit"`,
  rekomendasi: `Rekomendasi`,
  lihatSemuaProduk: `Lihat Semua Produk`,
  jualLimbah: `Jual Limbah`,
  transfer: `Transfer`,
  isiSaldo: `Isi Saldo`,
  lokasiSaatIni: `Lokasi Saat Ini`,
  tentukanLokasi: `Tentukan Lokasi`,
  pengolahanLimbah: `Pengolahan Limbah`,
  kategori: `Kategori`,
  beritaDanInformasi: `Berita dan Informasi`,
  diverifikasi: `Diverifikasi`,
  beli: `Beli`,
  jual: `Jual`,
  selesai: `Selesai`,
  pesananSelesai: `Pesanan Selesai`,
  home: `Home`,
  transaksi: `Transaksi`,
  penjualan: `Penjualan`,
  pesan: `Pesan`,
  profil: `Profil`,
  jenisLimbah: `Jenis Limbah`,
  stokAwal: `Stok`,
  harga: `Harga`,
  kurir: `Kurir`,
  deskripsi: `Deskripsi`,
  fotoProduk: `Foto Produk`,
  keranjang: `Keranjang`,
  totalHarga: `Total Harga`,
  saring: `Filter`,
  urutkan: `Sort`,
  terjual: `Terjual`,
  pembelianMinimum: `Pembelian Minimum`,
  stok: `Stok`,
  biayaMulaiDari: `Biaya Mulai Dari`,
  produkTerkait: `Produk Terkait`,
  pesanan: `Pesanan`,
  siapKirim: `Siap Kirim`,
  aktif: `Aktif`,
  tidakAktif: `Tidak Aktif`,
  akun: `Akun`,
  riwayatSaldo: `Riwayat Saldo`,
  pengaturanAkun: `Pengaturan Akun`,
  aplikasi: `Aplikasi`,
  pengaturanAplikasi: `Pengaturan Aplikasi`,
  kebijakanPrivasi: `Kebijakan Privasi`,
  syaratDanKetentuan: `Syarat dan Ketentuan`,
  tentangKami: `Tentang Kami`,
  logout: `Log Out`,
  selesai: `Selesai`,
  dikonfirmasi: `Dikonfirmasi`,
  dibatalkan: 'Dibatalkan',
  daftarPenjualan: `Daftar Penjualan`,
  judulAlertGagal: `Oops`,
  errorEmailKosong: `Email tidak boleh kosong`,
  errorPasswordKosong: `Password tidak boleh kosong`,
  errorNamaLengkapKosong: `Nama Lengkap tidak boleh kosong`,
  errorNomorHPKosong: `Nomor HP tidak boleh kosong`,
  errorKonfirmasiPasswordKosong: `Konfirmasi Password tidak boleh kosong`,
  errorFormatEmail: `Format Email harus valid`,
  errorDigitNomorHP: `Nomor HP minimal 7 digit`,
  errorKonfirmasiPasswordTidakCocok: `Password tidak cocok`,
  masukkanPin: `Masukkan PIN`,
  masukkanUlangPin: `Masukkan ulang PIN`,
  pinTidakSama: `Pin Tidak Sama`,
  errorPasswordKurangDigit: `Password tidak boleh kurang dari 4 digit`,
  judulAlertBerhasil: `Berhasil`,
  signUpBerhasil: `Sign Up berhasil, silahkan melakukan log in`,
  notifikasi: `Notifikasi`,
  terakhirDikunjungi: `Terakhir Dikunjungi`,
  loginMenggunakanAkunLain: `Log in With Another Account`,
  signUpLagi: `Sign Up Lagi Disini`,
  cekEmailOtpResetPassword: `Silahkan cek email anda dan masukkan OTP untuk melakukan reset password`,
  resetPasswordBerhasil: `Reset Password berhasil, silahkan melakukan login dengan password baru anda`,
  resetPassword: `Reset Password`,
  silahkanBuatPasswordBaru: `Silahkan membuat password baru`,
  apakahAndaYakin: `Apakah Anda yakin?`,
  apakahAndaYakinSignUp: `Apakah Anda yakin ingin membatalkan verifikasi Sign Up? Verifikasi dapat dilakukan lagi setelah login`,
  apakahAndaYakinResetPassword: `Apakah Anda yakin ingin membatalkan verifikasi Reset Password?`,
  apakahAndaYakinLogin: `Apakah Anda yakin ingin membatalkan verifikasi Log in? Verifikasi OTP dibutuhkan untuk melanjutkan pemakaian aplikasi`,
  silahkanKetikProdukYangDicari: `Silahkan ketik produk yang dicari`,
  produkTidakDitemukan: `Produk tidak ditemukan`,
  namaProduk: `Nama Produk`,
  kirimUlangOtp: `Kirim ulang OTP`,
  cekEmailUntukOtp: `Cek email anda untuk kode OTP`,
  sebelumMelanjutkanBuatPin: `Sebelum melanjutkan, anda harus membuat PIN demi keamanan dan kenyamanan anda dalam bertransaksi`,
  lanjut: `Lanjut`,
  selamatDatangdiUseIt: `Selamat datang di Use it, anda dapat melakukan berbagai transaksi terkait limbah disini`,
  apakahAndaYakinKeluar: `Apakah Anda yakin ingin keluar dari Use it?`,
  namaPenjual: 'Nama Penjual',
  namaTokoAtauLembaga: 'Nama Toko / Lembaga',
  alamat: `Alamat`,
  satuan: `Satuan`,
  ya: 'Ya',
  tidak: 'Tidak',
  apakahAndaYakinHapusGambar: 'Apakah Anda yakin ingin menghapus gambar',
  produk: `Produk`,
  cartKosong: `Cart Kosong`,
  apakahandaYakinHapusProduk: `Apakah anda yakin ingin menghapus produk`,
  apakahAndaYakinHapusCart: `Apakah anda yakin ingin menghapus cart`,
  andaHarusLogin: 'Anda harus log in atau sign up untuk menggunakan fitur ini',
  tidakSekarang: 'Tidak sekarang',
  kategoriTidakDitemukan: 'Kategori tidak ditemukan',
  dataBelumTersedia: 'Data belum tersedia',
  tambahProduk: 'Tambah Produk',
  kuantitas: 'Kuantitas',
  perkiraanKuantitas: 'Perkiraan Kuantitas',
};
